apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f31jvki4w-java-springboot 
  janus-idp.io/tekton: f31jvki4w-java-springboot
  backstage.io/kubernetes-id: f31jvki4w-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f31jvki4w-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml